source "https://api.berkshelf.com"

metadata

cookbook 'jira', git: 'https://github.com/bflad/chef-jira.git', tag: '2.0.1'
cookbook 'nexus', git: 'https://github.com/RiotGames/nexus-cookbook', tag: '3.3.0'
cookbook 'ssl_certificates', git: 'https://github.com/TYPO3-cookbooks/ssl_certificates.git'
cookbook 'gerrit', git: 'https://github.com/TYPO3-cookbooks/gerrit.git', tag: '0.3.2'
cookbook 'jenkins', git: 'https://github.com/opscode-cookbooks/jenkins', tag: 'v2.1.2'
cookbook 'openldap', '1.12.10'
cookbook 'java', '1.22.0'
cookbook 'sonar', '0.0.6', git: 'https://github.com/GreyTeardrop/chef-sonarqube.git'
cookbook 'nginx', git: 'https://github.com/miketheman/nginx.git', tag: 'v2.7.4'
cookbook 'chef-zephyr', '0.0.1', git: 'https://github.com/gsilantyev/chef-zephyr.git'
